[project]
name = "synapse"
version = "0.1.0"
description = "Client library and CLI for the Synapse API"
authors = [
    {name = "Science Team", email = "team@science.xyz"},
]
dependencies = [
    "grpcio-tools",
    "protoletariat",
    "serial"
]
readme = "README.md"
license = {text = "TBD"}

[tool.pdm.dev-dependencies]
dev = [
]

[tool.pdm]
distribution = false

[project.scripts]
synapsectl = "synapse.cli.main:main"