name: build

on:
  pull_request:
  push:
    tags:
      - 'v*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.22.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Test wheels in virtual environments
        run: |
          for wheel in wheelhouse/*.whl; do
            # Skip PyPy wheels for now (they need different handling)
            if [[ $wheel == *"pypy"* ]]; then
              echo "Skipping PyPy wheel: $wheel"
              continue
            fi
            
            # Extract Python version from wheel name
            if [[ $wheel =~ cp([0-9]{2}) ]]; then
              PY_VERSION="${BASH_REMATCH[1]}"
              echo "Testing wheel $wheel with Python 3.${PY_VERSION}"
              
              # Create new venv for this wheel
              python3.${PY_VERSION} -m venv .venv-${PY_VERSION}
              source .venv-${PY_VERSION}/bin/activate
              
              # Install and test wheel
              pip install "$wheel"
              python -c "import synapse"
              deactivate
              
              # Clean up
              rm -rf .venv-${PY_VERSION}
            fi
          done

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish:
    name: Upload wheels to PyPI
    needs: [build_wheels]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://testpypi.org/p/science-synapse
    permissions:
      id-token: write
    if: false
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-wheels-*
          path: dist
          merge-multiple: true

      - name: List wheels
        run: ls -la dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
