name: main

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential libprotobuf-dev protobuf-compiler
          sudo apt-get install -y libgrpc++-dev protobuf-compiler-grpc

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Build project
        run: |
          export Protobuf_INCLUDE_DIR=/usr/include
          export Protobuf_LIBRARIES=/usr/lib/x86_64-linux-gnu/libprotobuf.so
          make
          python -m build -v
        env:
          DISTUTILS_DEBUG: 1
          CMAKE_PREFIX_PATH: /usr

      - name: Install wheel
        run: |
          pip install dist/*.whl

      - name: Run tests with pytest
        run: |
          pytest -v
