name: main

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev 
          uv run make

      - name: Run tests with pytest
        run: |
          pytest -v

  test-examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.6"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
          uv run make

      - name: Run examples
        run: |
          uv run synapse-sim --iface-ip 127.0.0.1 --rpc-port 50051 &

          sleep 2

          uv run synapse/examples/stream_out.py 127.0.0.1:50051

          kill $(jobs -p)
