name: main

on:
  pull_request:
  push:
    tags:
      - "v*"

permissions:
  id-token: write

jobs:
  test-pypi-release:
    uses: ./.github/workflows/build.yml
    secrets:
      registry-token: ${{ secrets.TEST_PYPI_TOKEN }}
    with:
      registry-name: "testpypi"
      registry-url: "https://test.pypi.org/legacy/"
      package-url: "https://test.pypi.org/project/science-synapse/"

  validate-test-pypi-release:
    runs-on: ubuntu-latest
    needs: test-pypi-release
    steps:
      - name: install test pypi release
        run: |
          pip install --index-url https://test.pypi.org/simple/ science-synapse==v1.0.1-rc.2

      - name: run examples
        run: |
          synapse-sim --iface-ip 127.0.0.1 --rpc-port 50051 &
          sleep 2
          python synapse/examples/stream_out.py 127.0.0.1:50051
          kill $(jobs -p)

  # pypi-release:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     registry-name: "pypi"
  #     registry-url: "https://upload.pypi.org/legacy/"
  #     package-url: "https://pypi.org/project/science-synapse/"
  #   secrets:
  #     registry-token: ${{ secrets.PYPI_TOKEN }}
  #   needs: validate-test-pypi-release
