name: main

on:
  pull_request:
  push:
    tags:
      - "v*"

permissions:
  id-token: write

jobs:
  test-pypi-release:
    uses: ./.github/workflows/build.yml
    with:
      registry-name: "testpypi"
      registry-url: "https://test.pypi.org/legacy/"
      package-url: "https://test.pypi.org/project/science-synapse/"
      registry-token: ${{ secrets.TEST_PYPI_TOKEN }}

  # pypi-release:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     registry-name: "pypi"
  #     registry-url: "https://pypi.org/p/"
  #     package-url: "https://pypi.org/project/science-synapse/"
  #     registry-token: ${{ secrets.PYPI_TOKEN }}
  #   needs: test-pypi-release
