name: main

on:
  pull_request:
  push:
    tags:
      - "v*"

permissions:
  id-token: write

jobs:
  test-pypi-release:
    uses: ./.github/workflows/build.yml
    with:
      registry-name: "testpypi"
      registry-url: "https://test.pypi.org/legacy/"

  # pypi-release:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     registry-name: "pypi"
  #     registry-url: "https://pypi.org/p/"
  #   needs: test-pypi-release
